test-buffer: buffer.hpp
	./test-buffer
	rm test-buffer
buffer.hpp:
	g++ buffer.cpp -O3 -I ../include -o test-buffer


test-buffer: buffer.hpp
	./test-buffer
	rm test-buffer
buffer.hpp:
	g++ buffer.cpp -O3 -I ../include -o test-buffer
